### ISSUE TITLE
the crossposter just sorta.... crashes a lot

### ISSUE THREAD

**Issue by Lana-chan** [theZacAttacks/TwitPoster#3]
sometimes for one reason or another the crossposter can't post and it just crashes

recommend wrapping posting functions in a try-catch block

example traceback:

```
Traceback (most recent call last):
        18: from main.rb:68:in `<main>'
        17: from /home/erin/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/moostodon-0.4.0/lib/mastodon/streaming/client.rb:35:in `user'
        16: from /home/erin/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/moostodon-0.4.0/lib/mastodon/streaming/client.rb:94:in `stream'
        15: from /home/erin/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/moostodon-0.4.0/lib/mastodon/streaming/client.rb:127:in `request'
        14: from /home/erin/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/moostodon-0.4.0/lib/mastodon/streaming/connection.rb:26:in `stream'
        13: from /home/erin/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/moostodon-0.4.0/lib/mastodon/streaming/response.rb:23:in `<<'
        12: from /home/erin/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/moostodon-0.4.0/lib/mastodon/streaming/response.rb:23:in `<<'
        11: from /home/erin/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/moostodon-0.4.0/lib/mastodon/streaming/response.rb:33:in `on_body'
        10: from /home/erin/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/moostodon-0.4.0/lib/mastodon/streaming/response.rb:33:in `each'
         9: from /home/erin/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/moostodon-0.4.0/lib/mastodon/streaming/response.rb:40:in `block in on_body'
         8: from /home/erin/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/moostodon-0.4.0/lib/mastodon/streaming/client.rb:123:in `block in request'
         7: from main.rb:90:in `block in <main>'
         6: from /home/erin/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/rest/tweets.rb:126:in `update'
         5: from /home/erin/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/rest/tweets.rb:155:in `update!'
         4: from /home/erin/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/rest/utils.rb:64:in `perform_post_with_object'
         3: from /home/erin/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/rest/utils.rb:72:in `perform_request_with_object'
         2: from /home/erin/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/rest/utils.rb:50:in `perform_request'
         1: from /home/erin/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/rest/request.rb:39:in `perform'
/home/erin/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/rest/request.rb:81:in `fail_or_return_response_body': Could not authenticate you. (Twitter::Error::Unauthorized)```

**Comment by Lana-chan** [comment]
note: despite this saying it's an authorization error i have no idea why it did that. restarting the crossposter with absolutely no changes made it work again without problem

**Comment by compufox** [comment]
yeah, random ssl connection errors happen, too. :/

**Comment by compufox** [comment]
hopefully fixed? got some nice little rescue clauses in there for mastodon/twitter errors

**Comment by Lana-chan** [comment]
closing for now :)
